application: sflandmarks
version: feed-me-seymour
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /css
  static_dir: webapp/css

- url: /js
  static_dir: webapp/js

- url: /images
  static_dir: webapp/images

- url: /admin
  script: main.application
  login: admin

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
